---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: accountid.dkr.ecr.region.amazonaws.com/frontend:v14
        imagePullPolicy: Always
        ports:
        - containerPort: 4173
        env:
        - name: VITE_API_URL
          value: http://mongoapi.example.com/
