# mongo-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend # This is the hostname backend will use
spec:
  selector:
    app: backend
  ports:
  - port: 5050
    targetPort: 5050
  type: NodePort
